server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: issue-service
          uri: lb://issue-service
          predicates:
            - Path=/api/issues/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**
  springdoc:
    swagger-ui:
      disable-swagger-default-url: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
