server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      forwarded-headers-strategy: native
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: issue-service
          uri: lb://issue-service
          predicates:
            - Path=/issues/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: dashboard-service
          uri: lb://dashboard-service
          predicates:
            - Path=/dashboard/**

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
