server:
  port: 8082

spring:
  application:
    name: issue-service

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET}


management:
  endpoints:
    web:
      exposure:
        include: health, info
