server:
  port: 8083

spring:
  application:
    name: media-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, info
