server:
  port: 8081   # random port, Eureka will register

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${ACCESS}     # 15 minutes
    refresh: ${REFRESH} # 7 days


management:
  endpoints:
    web:
      exposure:
        include: health, info
