server:
  port: 8081

app:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASS}


spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${ACCESS}     # 15 minutes
    refresh: ${REFRESH} # 7 days


management:
  endpoints:
    web:
      exposure:
        include: health, info
